### ISSUE TITLE
What is the link to the journal article in Special Works Project 1?

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/advgis-beta#1]
I've been having some trouble finding a link the article that's mentioned for this project. Can anyone help?

**Comment by Steranso** [comment]
The link to the article for the project is:    https://gmd.copernicus.org/articles/10/689/2017/gmd-10-689-2017.pdf
The specific figure is on page 10 of the PDF, which is also numbered 698 in the top left corner.
