### ISSUE TITLE
looking for ocean temperature data

### ISSUE THREAD

**Issue by pmkinton** [cga-wm/advgis-beta#20]
Trying to use ocean temperatures on my Project A, specifically around South Africa, and I keep coming up empty-handed left and right. Anyone have any suggestions on where I can find some good ocean temp data for GIS? Appreciate any leads!

**Comment by dt-woods** [comment]
EarthData's Distributed Active Archive Centers (DAAC) have loads of data. You will have to create an account, but it's free. Once you do, I suggest checking out [PODAAC](https://podaac.jpl.nasa.gov/SeaSurfaceTemperature).
