### ISSUE TITLE
Where can we find the climate classification data for Special Works project 1?

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/advgis-beta#4]
We need access to a spatial dataset for the climate classification map. Anyone know where we can find it?

**Comment by pmkinton** [comment]
Found some downloadable koeppen-geiger data here: [http://koeppen-geiger.vu-wien.ac.at/shifts.htm](url) and the legend can be found here: [ http://koeppen-geiger.vu-wien.ac.at/data/legend.txt](url)

I downloaded the 1976-2000 data and added it to the map I previously shared with the AGOL group. Not sure if it's what we are looking for as a group, but it seems close to the figure 3 map.

**Comment by parthree** [comment]
Did you use Notebooks to do any of this?

**Comment by pmkinton** [comment]
I did not. Truthfully still figuring out Notebooks, but can try to go back and figure out how to put this in that.

**Comment by parthree** [comment]
Ok. Good, lol!  Me too.

**Comment by pmkinton** [comment]
Just put it into a notebook and shared it with the group.. hopefully that helps?

**Comment by dt-woods** [comment]
I see it! Please remember to add summaries and descriptions in your AGOL items; this will help clarify what each item consists of.
