### ISSUE TITLE
Create point data represented in Special Works Project 1

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/advgis-beta#5]
There are six points on Fig. 3 with coordinates given in the caption. Can anyone create this as spatial data? If so, please share in our AGOL group.

**Comment by dt-woods** [comment]
Found this in the supplemental material. Thought it might be helpful.

|ID|  REGION   |           ELV |  LON  |     LAT |    GRIDCODE  |  DESCRIPTION |
|--|  ------   |           ----: | ------: |  ----: |  -------- |   ----------- |
|a|   Banff, Alberta   |   1383 |  -116.500 | 51.800 | 62 (ET) |    tundra
|b|   Saranac, NY      |    383 |  -73.774 | 44.654 | 42 (Dfb)  |  continental w/ warm summer
|c|   San Francisco, CA |    16 |  -122.417 | 37.783 | 35 (Csb) |   warm temperate w/ warm dry summers
|d|   Yuma, AZ          |    43  | -114.615 | 32.692 | 22 (BWh)  |  hot arid desert
|e |  Penbroke Pines, FL |    2 |  -80.316 | 26.011  |12 (Am)   |  equitorial monsoonal
|f   |San Luis Potosi, MX | 1850 | -100.971 | 22.157 | 26 (BSk) |   cold arid steppe

**Comment by pmkinton** [comment]
Made this a CSV and added the data to a map in ArcGIS online. Here is the link for the map - should be shared with everyone at W&M. https://arcg.is/18jPvT0

**Comment by pmkinton** [comment]
Also shared it with the group on AGOL.
