### ISSUE TITLE
Quick Face-to-Name Introduction?

### ISSUE THREAD

**Issue by pmkinton** [cga-wm/advgis-beta#6]
hey y'all - I know that we already posted our introductions to the discussion post, but I was wondering if anyone else would find it helpful to have some quick face-to-face time with one another. I think it could be nice to be able to connect a faces to names since we are teammates for this class. 

Let me know if that's something y'all would be into.

**Comment by parthree** [comment]
That sounds good!  Maybe come up with a short list of talking points for everyone to contribute and ask specific questions about in addition to introducing ourselves.

**Comment by pmkinton** [comment]
Sounds good - perhaps shoot for Monday at 10:00 during office hours.

**Comment by dt-woods** [comment]
@pmkinton - were you creating a new meeting or do you want to use the Zoom meeting I have already created for office hours?

**Comment by pmkinton** [comment]
I was planning on using the already existing Zoom meeting, if that's alright. If not, I can set up a new one and share the link.

**Comment by dt-woods** [comment]
That works!
