### ISSUE TITLE
Special Project #1 How exact do we want this figure reproduction?

### ISSUE THREAD

**Issue by parthree** [cga-wm/advgis-beta#7]
From what I know about ArcGIS Online, admittedly limited, I couldn't recreate the look of this map there.  I'm gonna try in Pro and then share online.  Standby.  Thanks Peter for the links to the data sources!

**Comment by pmkinton** [comment]
Let me know how far you get on Pro and I can try and play around and see how far we can get. I imagine we are trying to get as close as possible.

**Comment by Steranso** [comment]
A problem I ran into on this route was Arc Online would not add the KML data to the map if you used the highest resolution option and shared it from ArcPro. Not sure if there was some sort of error on my end but just something to be aware of.

**Comment by parthree** [comment]
I don't have much experience with KML data, but that's good to know.  I noticed after the fact that the climate site offered the files as KML and thought maybe that would have been an easier route.  Perhaps not!  :-)

I used the shapefile data for the most recent time period in Pro, then color-coded it close to what the figure looked like, then shared as web layer.
