### ISSUE TITLE
Can you edit someone else's shared Notebook in AGOL?

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/advgis-beta#9]
Can anyone confirm the ability to open/edit someone else's shared Notebook? 
Please refrain from the temptation to open, select all, and delete someone else's work ;)

**Comment by pmkinton** [comment]
I was able to open @parthree's Special Works Project #1 notebook and edit, but once I went to save, I could only save as a copy  as part of my own content and not as part of the original notebook.

**Comment by parthree** [comment]
Samesies.  Only option is Save As.

**Comment by dt-woods** [comment]
That's not the worst thing, but good to know. Thanks!
